name: gestionmedicamentos
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  bcrypt: ^1.1.3
  supabase_flutter: ^2.6.0
  path: ^1.9.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  mobile_scanner: ^3.2.0  
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^9.2.2
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
